import { createRoot } from "react-dom/client";
import { useRoute, useLocation } from "wouter";
import "./index.css";
import { Logo } from "@pmndrs/branding";
import { App } from "./App";

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

function Root() {
  const [, params] = useRoute("/item/:id");
  const [, setLocation] = useLocation();

  return (
    <>
      <App />
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: "100%",
        }}
      >
        <a
          href="https://pmnd.rs/"
          style={{
            position: "absolute",
            bottom: 30,
            left: 70,
            fontSize: "11px",
          }}
        >
          ciaran okeeffe
          <br />
          developer
        </a>
        <div
          style={{
            position: "absolute",
            bottom: 30,
            right: 25,
            fontSize: "11px",
          }}
        >
          gitHub
        </div>
        <Logo
          style={{ position: "absolute", bottom: 30, left: 25, width: 30 }}
        />
        <a
          style={{ position: "absolute", top: 20, left: 25, fontSize: "11px" }}
          href="#"
          onClick={() => setLocation("/")}
        >
          {params ? "< back" : "drag to spin, tap frames to view"}
        </a>
      </div>{" "}
    </>
  );
}

createRoot(document.getElementById("root")!).render(<Root />);

// ReactDOM.createRoot(document.getElementById('root')).render(<App />)
// replacement:
// ReactDOM.createRoot(document.getElementById('root')).render(<RouterProvider router={mainRouter} />)
