import { createRoot } from "react-dom/client";
// import { useRoute, useLocation } from "wouter";
import "./index.css";
// import "./styles.css";
// import { Logo } from "@pmndrs/branding";
import { App } from "./App";
// import ViewInArIcon from "@mui/icons-material/ViewInAr";
// import DataArrayIcon from "@mui/icons-material/DataArray";
// import TextureIcon from "@mui/icons-material/Texture";
// import VerticalShadesClosedIcon from "@mui/icons-material/VerticalShadesClosed";
import WavesIcon from "@mui/icons-material/Waves";

/*
Model JSX auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform --simplify --resolution=2048
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

function Root() {
  // const [, params] = useRoute("/item/:id");
  // const [, setLocation] = useLocation();

  return (
    <>
      <App />
      <div
        style={{
          position: "absolute",
          top: 0,
          left: 0,
          width: "100%",
          height: "100%",
        }}
      >
        <a
          href="https://github.com/chairawn/"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            position: "absolute",
            top: 30,
            left: 63,
            fontSize: "11px",
          }}
        >
          ciaran okeeffe
          <br />
          developer
        </a>
        <a
          href="https://github.com/chairawn/"
          target="_blank"
          rel="noopener noreferrer"
          style={{
            position: "absolute",
            top: 30,
            right: 25,
            fontSize: "11px",
          }}
        >
          gitHub
        </a>
        <WavesIcon
          style={{ position: "absolute", top: 30, left: 25, width: 30 }}
        />
      </div>
      <div
        id="footer"
        style={{
          position: "absolute",
          bottom: 30,
          left: "50%",
          width: 75,
          fontSize: "0.75rem",
        }}
      ></div>
    </>
  );
}

createRoot(document.getElementById("root")!).render(<Root />);

// ReactDOM.createRoot(document.getElementById('root')).render(<App />)
// replacement:
// ReactDOM.createRoot(document.getElementById('root')).render(<RouterProvider router={mainRouter} />)
